#WORKING
CREATE TABLE TagsIDS (
    TagID VARCHAR(20) PRIMARY KEY,
    Tag VARCHAR(30)
);

INSERT INTO TagsIDS
(TagID, Tag)
VALUES
(0, 'Empty'),
(1,'Mystery'),
(2,'Thriller'),
(3,'Business'),
(4,'Horror'),
(5,'Fiction'),
(6,'Fantasy'),
(7,'Crafts & Hobbies'),
(8,'Gardening'),
(9,'Language And Literature'),
(10,'Sociology'),
(11,'Self Help'),
(12,'Finance'),
(13,'Health & Fitness'),
(14,'Young Adult'),
(15,'Classics'),
(16,'Romance'),
(17,'Poetry'),
(18,'Contemporary'),
(19,'Historical'),
(20,'Philosophy'),
(21,'Science Fiction'),
(22,'Humour'),
(23,'History'),
(24,'Reference'),
(25,'Psychology'),
(26,'Religion'),
(27,'Art'),
(28,'Foreign Exchange'),
(29,'Military'),
(30,'Spirituality'),
(31,'Writing'),
(32,'Biography'),
(33,'Computers'),
(34,'Science'),
(35,'Audiology & Speech Pathology'),
(36,'War'),
(37,'Politics'),
(38,'Suspense'),
(39,'Desktop Applications'),
(40,'Health'),
(41,'Thrillers'),
(42,'Encyclopedia'),
(43,'Adventure'),
(44,'Adventure'),
(45,'Action'),
(46,'Travel'),
(47,'Literary'),
(48,'Vampires'),
(49,'Personal Development'),
(50,'Anthology'),
(51,'Childrens'),
(52,'Japanese Culture'),
(53,'Economics')
;

