#working

CREATE DATABASE Library;
use Library;


CREATE TABLE UniqueID (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(200) NOT NULL,
    LastName VARCHAR(200),
    Title VARCHAR(200) NOT NULL,
    Series VARCHAR(100),
    Publisher VARCHAR(200)
);

INSERT INTO UniqueID(
FirstName, LastName,Title, Series, Publisher)
VALUES
('ROB','THOMAS','Veronica Mars 02.00 - Mr Kiss And Tell','Veronica Mars','Vintage'),
('ALAN','BRADLEY','As Chimney Sweepers Come To Dust','Flavia De Luce','Bantam'),
('CHRIS','RYAN','Battleground','Code Red','Doubleday'),
('HARVARD BUSINESS','REVIEW','On Emotional Intelligence (HbrS 10 Must Reads)','','Harvard Business Review Press'),
('RAYMOND','BENSON','Never Dream Of Dying','Raymond BensonS Bond','Jove'),
('DEAN','KOONTZ','Saint Odd','Odd Thomas','Bantam'),
('MIRA','GRANT','Rolling In The Deep','Rolling In The Deep','Subterranean'),
('JENNIFER','MCMAHON','The Night Sister','','Doubleday'),
('JEREMY','BATES','Suicide Forest','WorldS Scariest Places','Ghillinnein Books'),
('CHARLES','STROSS','The Annihilation Score','Laundry Files','Orbit'),
('ROBERT R.','MCCAMMON','The Border','','Subterranean Press'),
('S. K.','TREMAYNE','The Ice Twins','','HarperCollins UK'),
('C. J.','SANSOM','Lamentation','Matthew Shardlake','Mantle'),
('LOUISE','PENNY','The Nature Of The Beast','Chief Inspector Armand Gamache','Minotaur Books'),
('DANIEL','SILVA','The English Spy','Gabriel Allon','Harper'),
('PAULA','HAWKINS','The Girl On The Train','','Riverhead Books'),
('PAUL','TREMBLAY','A Head Full Of Ghosts','','William Morrow'),
('RICK','BEECH','The Practical Illustrated Encyclopedia Of Origami: The Complete Guide To The Art Of Paperfolding','','Lorenz Books'),
('MEGAN','GEORGE','Modern Terrarium Studio: Design + Build Custom Landscapes With Succulents, Air Plants + More','','Fons & Porter'),
('WILLIAM N. THORNDIKE','JR.','The Outsiders: Eight Unconventional Ceos And Their Radically Rational Blueprint For Success','','Harvard Business Review Press'),
('JOHN C.','BOGLE','The Clash Of The Cultures: Investment Vs. Speculation','','Wiley'),
('TIMOTHY F.','GEITHNER','Stress Test: Reflections On Financial Crises','','Crown'),
('LINCOLN','CHILD','Deep Storm','Jeremy Logan','Doubleday Books'),
('JOHN','BROOKS','Business Adventures: Twelve Classic Tales From The World Of Wall Street','','Open Road Media'),
('LAWRENCE A.','CUNNINGHAM','The Essays Of Warren Buffett: Lessons For Investors And Managers','','John Wiley & Sons'),
('MARTIN','HEWINGS','English Pronunciation In Use Advanced Book With Answers And Downloadable Audio','Pronunciation In Use','Cambridge University Press'),
('KATE','FOX','Watching The English: The Hidden Rules Of English Behaviour','','Hachette UK'),
('RICHARD','HOGGART','Everyday Language & Everyday Life','','Routledge'),
('BRIAN','DOLAN','Currency Trading For Dummies','','John Wiley & Sons'),
('OLIVIA FOX','CABANE','The Charisma Myth: How Anyone Can Master The Art And Science Of Personal Magnetism','','Portfolio'),
('JOHN L.','PERSON','A Complete Guide To Technical Trading Tactics: How To Profit Using Pivot Points, Candlesticks & Other Indicators','','John Wiley & Sons'),
('VICTORIA JORDAN','STONE','The WorldS Best Massage Techniques The Complete Illustrated Guide: Innovative Bodywork Practices From Around The Globe For Pleasure, Relaxation, And Pain Relief','','Fair Winds Press'),
('MICHELLE','KRYS','Hexed','The Witch Hunter','Delacorte Press'),
('DEBRA','FINE','The Fine Art Of Small Talk: How To Start A Conversation, Keep It Going, Build Networking Skills And Leave A Positive Impression!','','Hachette Books'),
('V. S.','NAIPAUL','In A Free State','','Picador USA'),
('SHIMMA J.','DAVID','Viking Rule','','Shimma J. David -Smashwords'),
('JOHN LE','CARRÉ','SmileyS People','George Smiley','Penguin UK'),
('STEPHEN','KING','Finders Keepers','Bill Hodges Trilogy',''),
('DASHIELL','HAMMETT','Red Harvest','The Continental Op','Vintage Books'),
('YASUNARI','KAWABATA','Beauty And Sadness','','Vintage'),
('JOHN KENNEDY','TOOLE','A Confederacy Of Dunces','','LSU Press'),
('ANTHONY','BURGESS','A Clockwork Orange','','Reclam'),
('ERNEST','HEMINGWAY','The Sun Also Rises','','Simon and Schuster'),
('ANAÏS','NIN','House Of Incest','','Swallow Press'),
('MILAN','KUNDERA','The Unbearable Lightness Of Being','','Faber & Faber'),
('PHILIP','ROTH','The Human Stain','Complete Nathan Zuckerman','Vintage Books'),
('THOMAS','KENEALLY','SchindlerS Ark','','Sceptre'),
('OSCAR','WILDE','The Picture Of Dorian Gray: Oscar Wilde - The Picture Of Dorian Gray: Volume 1 (Modern Library Classics)','','CreateSpace Independent Publishing Platform'),
('JOSEPH','CONRAD','The Shadow Line A Confession','','CreateSpace Independent Publishing Platform'),
('NORA','ROBERTS','Time Was','Time And Again: Hornblower-Stone','Harlequin Mills & Boon, Limited'),
('ALBERT','CAMUS','The Stranger','','Vintage International'),
('WILLIAM','SHAKESPEARE','Macbeth','','Simon  Schuster'),
('IRIS','MURDOCH','Under The Net','','Random House'),
('HAROLD R.','KERZNER','Project Management Best Practices: Achieving Global Excellence','','Wiley'),
('JAMES','JOYCE','Dubliners: By James Joyce - Illustrated','',''),
('J. R. R.','TOLKIEN','The Hobbit','The Hobbit','Houghton Mifflin'),
('DOUGLAS','ADAMS','The Long Dark Tea-Time Of The Soul','Dirk Gently','Pan Books'),
('MELISSA','FOSTER','Sisters In Love','Snow Sisters','World Literary Press'),
('SETH','GRAHAME-SMITH','The Last American Vampire','Abraham Lincoln: Vampire Hunter','Grand Central Publishing'),
('CLIVE','BARKER','The Scarlet Gospels','Hellraiser','St. Martins Press'),
('PAULO','COELHO','Manuscript Found In Accra','','Knopf'),
('P. D.','JAMES','The Skull Beneath The Skin','Cordelia Gray','Warner Books'),
('MARGARET','ATWOOD','The Blind Assassin','Booker Winners','Anchor'),
('KAZUO','ISHIGURO','Never Let Me Go','Ishiguro Bibliography','Faber & Faber'),
('IAN','MCEWAN','The Cement Garden','','Anchor'),
('LEO','TOLSTOY','The Death Of Ivan Ilych','','Waking Lion Press'),
('TONI','MORRISON','Sula','','Random House'),
('MARQUÉS DE','SADE','Justine (Isla De Barataria)','Erotico','Exilado'),
('H. P.','LOVECRAFT','At The Mountains Of Madness','','Modern Library'),
('CATHY','MACPHAIL','Bad Company','','Bloomsbury Publishing PLC'),
('CHESTER','HIMES','Blind Man With A Pistol','Harlem Cycle','Vintage Books'),
('SEBASTIAN','FAULKS','Devil May Care','James Bond - Extended Series','Penguin'),
('JACK','KEROUAC','On The Road','Duluoz Legend','Viking Adult'),
('LOUIS DE','BERNIÈRES','Captain CorelliS Mandolin','','Vintage'),
('CHICAGO','TRIBUNE','Life Skills: How To Do Almost Anything','','Agate Midway'),
('CHUCK','PALAHNIUK','Choke','','Anchor Books'),
('SOPHIE','HANNAH','The Poetry Of Sex','','Penguin'),
('C. S.','LEWIS','The Lion, The Witch And The Wardrobe','The Chronicles Of Narnia (Publication Order)','HarperCollins'),
('CARL','SAGAN','Contact','','Arrow Books Ltd'),
('MAYA','ANGELOU','The Complete Collected Poems Of Maya Angelou','','Random House'),
('J. D.','ROBB','Obsession In Death','In Death','Berkley'),
('IAIN','BANKS','Complicity','','Simon  Schuster'),
('J. M.','COETZEE','Waiting For The Barbarians','','Vintage'),
('NEAL','STEPHENSON','Cryptonomicon','','Avon'),
('SALMAN','RUSHDIE','MidnightS Children','Booker Winners','Vintage'),
('JESSICA','CLARE','Stranded With A Billionaire','Billionaire Boys Club','Penguin Group (USA)'),
('BORIS','PASTERNAK','Doctor Zhivago','','Pantheon'),
('CHRISTOPHER','REICH','A Vingança','Jonathan Ransom','Editora Arqueiro'),
('MARY WOLLSTONECRAFT','SHELLEY','Frankenstein','','Oxford University Press'),
('J. A.','HUSS','Tragic','Rook And Ronin','Science Future Press'),
('MADDY','HUNTER','Fleur De Lies','Passport To Peril','MIDNIGHT INK'),
('ELMORE','LEONARD','Get Shorty','Chili Palmer','Dell'),
('SARAH','WATERS','Fingersmith','','Riverhead Books'),
('GORE','VIDAL','Myra Breckinridge','','Little, Brown & Company'),
('ANDREW','PESSIN','Filosofia Em 60 Segundos','','LEYA BRASIL'),
('AUGUSTO','CURY','Inteligência Multifocal','','Cultrix'),
('P. L.','TRAVERS','Mary Poppins: The Complete Collection','Mary Poppins','Harper Collins Childs'),
('ALEKSANDR','SOLZHENITSYN','In The First Circle','','Harper Perennial'),
('MINDY','MCGINNIS','In A Handful Of Dust','Not A Drop To Drink','Katherine Tegen Books'),
('YANN','MARTEL','Life Of Pi','','Mariner Books / Harvest Books'),
('DUNCAN','WILLIAMSON','Jack And The DevilS Purse: Scottish Traveller Tales','','Birlinn Ltd'),
('AMBORU KATO','KIMURA','The Ancient Art Of Bonsai','','Tree Society'),
('GABRIEL GARCÍA','MÁRQUEZ','The Autumn Of The Patriarch','','Penguin UK'),
('VLADIMIR','NABOKOV','Pale Fire','','Vintage'),
('MADELEINE','KUDERICK','Kiss Of Broken Glass','','HarperTeen'),
('JAY','POSEY','Morningside Fall','Legends Of The Duskwalker','Angry Robot'),
('J. K.','ROWLING','Harry Potter And The Deathly Hallows','Harry Potter','Arthur A. Levine Books'),
('BOB','KNIGHT','O Poder Extraordinário Do Pensamento Negativo (Portuguese Edition)','','Agir'),
('PATRICIA','HIGHSMITH','The Talented Mr Ripley','Ripley','Vintage'),
('H. PAUL','VARLEY','Japanese Culture, 4Th Edition','','University of Hawaii Press'),
('OLIVIA','LODISE','Violet Path','','BQB Publishing'),
('VIRGINIA','WOOLF','The Voyage Out','','Oxford University Press'),
('KEN','KESEY','One Flew Over The CuckooS Nest','','Penguin Books'),
('ELIZABETH','ANDOH','Washoku: Recipes From The Japanese Home Kitchen','','Ten Speed Press'),
('LAWRENCE','SANDERS','The Third Deadly Sin','The Edward X. Delaney','Berkley'),
('SUSAN','CAIN','Quiet: The Power Of Introverts In A World That CanT Stop Talking','','Crown'),
('MICHAEL','ONDAATJE','The English Patient','Booker Winners','Vintage'),
('KIKI','SULLIVAN','The Dolls','The Dolls','Balzer + Bray'),
('ANNIE','PROULX','The Shipping News','','Scribner Book Company'),
('GASTON','LEROUX','The Phantom Of The Opera: By Gaston Leroux : Illustrated','',''),
('KARIN','SLAUGHTER','Pretty Girls','','William Morrow'),
('NIKOS','KAZANTZAKIS','The Last Temptation Of Christ','','Simon  Schuster'),
('JIM','THOMPSON','The Killer Inside Me','','Orion'),
('LAURA C.','MARTIN','Tea: The Drink That Changed The World','','Tuttle Publishing'),
('IRVINE','WELSH','Trainspotting','Mark Renton','W.W. Norton'),
('ELISE','TIPTON','Modern Japan: A Social And Political History','','Routledge'),
('P. J.','YOUNG','To Be Honest','','Autharium'),
('MERVYN','PEAKE','Titus Groan','Gormenghast','Random House'),
('BARBARA J.','WEBB','City Of Burning Shadows','Apocrypha: The Dying World','Frontiers'),
('CHINUA','ACHEBE','Things Fall Apart','The African Trilogy','Penguin'),
('STEPHEN R.','TURNBULL','The Samurai Sourcebook','Japanese Culture','Cassell'),
('HARU YAMADA SENIOR LECTURER IN LINGUISTICS UNIVERSITY OF','WESTMINSTER','Different Games, Different Rules : Why Americans And Japanese Misunderstand Each Other: Why Americans And Japanese Misunderstand Each Other','Japanese Culture','Oxford University Press'),
('YEVGENY','ZAMYATIN','We','','Penguin UK'),
('SAMUEL','BECKETT','Waiting For Godot - En Attendant Godot','','Faber and Faber'),
('JOY','HENDRY','Understanding Japanese Society','','Routledge'),
('JEFF','KINGSTON','Contemporary Japan: History, Politics, And Social Change Since The 1980S','Blackwell History Of The Contemporary World','Wiley-Blackwell'),
('SUSAN J.','NAPIER','Anime From Akira To HowlS Moving Castle: Experiencing Contemporary Japanese Animation','Japanese Culture','Palgrave MacMillan'),
('OLIVIER','BLANCHARD','Macroeconomics','','Pearson Education'),
('CHARLES T.','MUNGER','Poor CharlieS Almanack: The Wit And Wisdom Of Charles T. Munger','','Donning Company Pub.'),
('DON','SNELLGROVE','Selective Forex Trading: How To Achieve Over 100 Trades In A Row Without A Loss','','Wiley'),
('KATHY','LIEN','Millionaire Traders: How Everyday People Are Beating Wall Street At Its Own Game','','John Wiley & Sons'),
('MUTSUKO','TOKUNAGA','New Tastes In Green Tea: A Novel Flavor For Familiar Drinks, Dishes, And Desserts','','Kodansha International'),
('CALLUM','HENDERSON','Currency Strategy A PractitionerS Guide To Currency Trading, Hedging And Forecasting','','John Wiley & Sons'),
('JOHN WHITNEY','HALL','The Cambridge History Of Japan V4','The Cambridge History Of Japan','Cambridge University Press'),
('WILLIAM A.','COHEN','Secrets Of Special Ops Leadership: Dare The Impossible -- Achieve The Extraordinary','','AMACOM/American Management Association'),
('EDWARD DE','BONO','Think!: Before ItS Too Late','','Vermilion'),
('TONY','HSIEH','Delivering Happiness: A Path To Profits, Passion, And Purpose','','Grand Central Publishing'),
('VIKTOR E.','FRANKL','ManS Search For Meaning','','Beacon Press'),
('TOM','RATH','Strengthsfinder 2.0','','Gallup Press'),
('SUSAN JANE','GILMAN','Kiss My Tiara: How To Rule The World As A Smartmouth Goddess','','Hachette UK'),
('SUSAN FAY','WEST','Organize For A Fresh Start: Embrace Your Next Chapter In Life','','F+W Media'),
('SURYA','DAS','Awakening The Buddha Within : Eight Steps To Enlightenment: Tibetan Wisdom For The Western World','','Random House Audio'),
('STEVEN','PRESSFIELD','The War Of Art','','Rugged Land'),
('SPENCER','JOHNSON','Who Moved My Cheese?: An Amazing Way To Deal With Change In Your Work And In Your Life','Who Moved My Cheese?','Vermilion'),
('SHARON','SALZBERG','Real Happiness: The Power Of Meditation: A 28-Day Program','','Workman Publishing Company'),
('SHERRY','ARGOV','Why Men Love Bitches: From Doormat To Dreamgirl—A WomanS Guide To Holding Her Own In A Relationship','','Adams Media'),
('SHAMA','KABANI','The Zen Of Social Media Marketing: An Easier Way To Build Credibility, Generate Buzz, And Increase Revenue','','BenBella Books'),
('SEAN','BRODRICK','The Ultimate Suburban Survivalist Guide: The Smartest Money Moves To Prepare For Any Crisis','','Wiley'),
('SCOTT','BELSKY','Making Ideas Happen: Overcoming The Obstacles Between Vision And Reality','','Portfolio'),
('ROY','LILLEY','Dealing With Difficult People (Creating Success)','','Kogan Page'),
('ROBERT','HOLDEN','Happiness Now!: Timeless Wisdom For Feeling Good Fast','','Hay House'),
('RECIPES365','COOKBOOKS','The Big Ketogenic Cookbook: Delicious & Nutritious Keto Diet Recipes: High Fat Low Carb Cookbook For Breakfast, Lunch, Dinner & Dessert','','CreateSpace Independent Publishing Platform'),
('RAMIT','SETHI','I Will Teach You To Be Rich: No Guilt. No Excuses. No Bs. Just A 6-Week Program That Works','','Workman Publishing Company'),
('PETER F.','DRUCKER','Innovation And Entrepreneurship','','HarperCollins e-books'),
('PEMA','CHÖDRÖN','Taking The Leap: Freeing Ourselves From Old Habits And Fears','','Shambhala'),
('NLP','COMPREHENSIVE','Nlp: New Technology: The New Technology','','William Morrow Paperbacks'),
('NICHOLAS','BOOTHMAN','How To Make People Like You In 90 Seconds Or Less','','Workman Publishing Company'),
('NEIL','STRAUSS','The Game','','Canongate Books Ltd'),
('NEIL A.','FIORE','The Now Habit At Work: Perform Optimally, Maintain Focus, And Ignite Motivation In Yourself And Others','','Wiley'),
('NANCY','ORTBERG','Unleashing The Power Of Rubber Bands: Lessons In Non-Linear Leadership','','Tyndale Momentum'),
('MIHALY','CSIKSZENTMIHALYI','Good Business: Leadership, Flow, And The Making Of Meaning','','Penguin Books'),
('MAXWELL','MALTZ','Psycho-Cybernetics','','Pocket'),
('MARY','PIPHER','Reviving Ophelia: Saving The Selves Of Adolescent Girls','','Riverhead Books'),
('MARTIN E. P.','SELIGMAN','What You Can Change . . . And What You CanT* What You Can Change . . . And What You CanT*','','Vintage Books USA'),
('MALCOLM','GLADWELL','What The Dog Saw And Other Adventures','','Little, Brown and Company'),
('M. SCOTT','PECK','The Road Less Traveled And Beyond: Spiritual Growth In An Age Of Anxiety','','Touchstone'),
('LUKE','BARR','Ritz And Escoffier: The Hotelier, The Chef, And The Rise Of The Leisure Class','','Clarkson Potter Publishers'),
('LINDA K.','ROLIE','Getting Back To Work: Everything You Need To Bounce Back And Get A Job After A Layoff','','McGraw-Hill Education'),
('LEIL','LOWNDES','How To Talk To Anyone: 92 Little Tricks For Big Success In Relationships','','Contemporary Books'),
('LEANDER','KAHNEY','Inside SteveS Brain, Expanded Edition','','Portfolio'),
('LAURIE A.','HELGOE','Introvert Power: Why Your Inner Life Is Your Hidden Strength','','Sourcebooks'),
('LAURENCE G.','BOLDT','Zen And The Art Of Making A Living: A Practical Guide To Creative Career Design','','Penguin Books'),
('KATHLEEN','SCHIENLE','Best Practices: Achieving Goals: Define And Surpass Your High Performance Goals','','HarperCollins e-books'),
('KAREN','ARMSTRONG','Twelve Steps To A Compassionate Life','','Knopf'),
('JOSH','KAUFMAN','The Personal Mba: Master The Art Of Business','','Portfolio'),
('JOSÉ','UNPINGCO','Python For Probability, Statistics, And Machine Learning','','Springer'),
('JONAH','LEHRER','How We Decide','','Houghton Mifflin Company'),
('JOHN ELDER','ROBISON','Be Different: Adventures Of A Free-Range Aspergian With Practical Advice For Aspergians, Misfits, Families & Teachers','','Crown'),
('JENNIFER MICHAEL','HECHT','The Happiness Myth: The Historical Antidote To What IsnT Working Today','','HarperOne'),
('JEFFREY','PFEFFER','Power: Why Some People Have It And Others DonT','','Harper Business'),
('JEFFREY G.','ALLEN','Instant Interviews','','Wiley'),
('JAMES D.','WATSON','Avoid Boring People: Lessons From A Life In Science','','Vintage'),
('JAMES C.','COLLINS','Good To Great: Why Some Companies Make The Leap...And Others DonT','','Harper Business'),
('IRENE S.','LEVINE','Best Friends Forever: Surviving A Breakup With Your Best Friend','','Overlook Press'),
('HILL','HARPER','Letters To A Young Brother: Manifest Your Destiny','','Penguin'),
('HELEN','FIELDING','Bridget JonesS Baby: The Diaries','Bridget Jones','Knopf Publishing Group'),
('HAROLD S.','KUSHNER','Conquering Fear: Living Boldly In An Uncertain World','','Alfred A. Knopf'),
('GUY','KAWASAKI','Enchantment: The Art Of Changing Hearts, Minds, And Actions','','Portfolio'),
('GEOFF','COLVIN','Talent Is Overrated: What Really Separates World-Class Performers From Everybody Else','','Portfolio'),
('GAYLE LAAKMANN','MCDOWELL','The Google Resume: How To Prepare For A Career And Land A Job At Apple, Microsoft, Google, Or Any Top Tech Company','','Wiley'),
('GAVIN DE','BECKER','The Gift Of Fear: Survival Signals That Protect Us From Violence','','Recorded Books'),
('GARY','VAYNERCHUK','Crush It!: Why Now Is The Time To Cash In On Your Passion','','HarperCollins'),
('ERIC','RIES','The Lean Startup: How TodayS Entrepreneurs Use Continuous Innovation To Create Radically Successful Businesses','','Crown'),
('ELAINE','ARON','The Highly Sensitive Person','','Kensington Publishing Corporation'),
('ECKHART','TOLLE','The Power Of Now: A Guide To Spiritual Enlightenment','','New World Library'),
('DOV','SEIDMAN','How: Why How We Do Anything Means Everything...In Business (And In Life)','','Wiley'),
('DUANE','ELGIN','Voluntary Simplicity: Toward A Way Of Life That Is Outwardly Simple, Inwardly Rich','','Harper Collins'),
('DONALD R.','KEOUGH','The Ten Commandments For Business Failure','','Portfolio'),
('DK','PUBLISHING','Japanese English Visual Bilingual Dictionary','','DK Pub.'),
('DEEPAK','CHOPRA','The Book Of Secrets','','Rider'),
('DAWN ROSENBERG','MCKAY','The Everything Practice Interview Book: Be Prepared For Any Question','','Everything'),
('DAVE','MCGUIRE','Beyond Stammering: The Mcguire Programme For Getting Good At The Sport Of Speaking','','Not Avail'),
('DANIEL TODD','GILBERT','Stumbling On Happiness','','Vintage'),
('DANIEL J.','SIEGEL','Mindsight: The New Science Of Personal Transformation','','Bantam'),
('DANIEL H.','PINK','A Whole New Mind: Why Right-Brainers Will Rule The Future','','Riverhead Books'),
('DANIEL G.','AMEN','Change Your Brain, Change Your Life: The Breakthrough Program For Conquering Anxiety, Depression, Obsessiveness, Anger, And Impulsiveness','','Harmony'),
('DAN','ARIELY','The Upside Of Irrationality','','HarperCollins'),
('DALE','CARNEGIE','How To Win Friends And Influence People','','Simon and Schuster'),
('CONOR','OCLERY','Billionaire Who WasnT: How Chuck Feeney Made And Gave Away A Fortune','','PublicAffairs'),
('CLAY','SHIRKY','Cognitive Surplus: Creativity And Generosity In A Connected Age','','Penguin Press'),
('CATHERINE','BLYTH','The Art Of Conversation: A Guided Tour Of A Neglected Pleasure','','Gotham'),
('BURTON G.','MALKIEL','A Random Walk Down Wall Street: The Time-Tested Strategy For Successful Investing (Tenth Edition)','','W. W. Norton & Company'),
('BENJAMIN','GRAHAM','The Intelligent Investor','','Harper Business'),
('BARRY','SILVERSTEIN','Best Practices: Motivating Employees: Bringing Out The Best In Your People','','Harper Collins'),
('BARNEY','STINSON','The Bro Code','','Simon and Schuster'),
('AUGUSTEN','BURROUGHS','This Is How','','Picador Australia'),
('BARBARA','EHRENREICH','Bright-Sided: How The Relentless Promotion Of Positive Thinking Has Undermined America','','Metropolitan Books'),
('B. ALAN','WALLACE','The Attention Revolution: Unlocking The Power Of The Focused Mind','','ReadHowYouWant.com'),
('ANODEA','JUDITH','Eastern Body, Western Mind: Psychology And The Chakra System As A Path To The Self','','Celestial Arts'),
('ANDREW S.','TREES','Decoding Love: Why It Takes Twelve Frogs To Find A Prince, And Other Revelations From The Science Of Attraction','','Avery'),
('ANDRÉ','KUKLA','Mental Traps: The OverthinkerS Guide To A Happier Life','','Anchor Canada'),
('ALAN W.','WATTS','The Book On The Taboo Against Knowing Who You Are','','Vintage'),
('ADAM','CAROLLA','In Fifty Years WeLl All Be Chicks . . . And Other Complaints From An Angry Middle-Aged White Guy','','Crown Archetype'),
('W. E. B.','GRIFFIN','Secret Honor','Honor Bound','G.P. Putnams Sons'),
('UMBERTO','ECO','FoucaultS Pendulum','','Mariner Books'),
('JEROME','PREISLER','Wild Card','Tom ClancyS Power Plays','Berkley'),
('DIANE','DUANE','Death Match','Tom ClancyS Net Force Explorers','Berkley'),
('BILL','MCCAY','Cold Case','Tom ClancyS Net Force Explorers','Headline Feature'),
('MEL','ODOM','Gameprey','Tom ClancyS Net Force Explorers','Berkley'),
('STEVE','PERRY','Changing Of The Guard','Tom ClancyS Net Force','Berkley'),
('STEPHENIE','MEYER','The Host: A Novel','','Little, Brown and Company'),
('RON','PAUL','The Revolution: A Manifesto','The Revolution: A Manifesto','Grand Central Publishing'),
('ROSS','MACDONALD','Black Money','Lew Archer','Vintage Crime/Black Lizard'),
('ROBIN','HOBB','Ship Of Magic','The Liveship Traders','Spectra'),
('ROBERT M.','PIRSIG','Zen And The Art Of Motorcycle Maintenance','Phaedrus','HarperPerennial'),
('ROBERT J.','SAWYER','Flashforward','','Tor Books'),
('RAY','BRADBURY','The Illustrated Man','','William Morrow'),
('PIERRE','BOULLE','Planet Of The Apes','','Del Rey'),
('PHYLLIS A.','WHITNEY','Secret Of Haunted Mesa','','Westminster Press'),
('PHILIP K.','DICK','Do Androids Dream Of Electric Sheep','','Oxford University Press'),
('PATRICK','ROTHFUSS','The Name Of The Wind','The Kingkiller Chronicle','Daw Books'),
('LEMONY','SNICKET','The Vile Village','A Series Of Unfortunate Events','Egmont'),
('LARRY','NIVEN','Ringworld','Ringworld','Ballantine Books'),
('KHALED','HOSSEINI','The Kite Runner','','Riverhead Books'),
('JON','KRAKAUER','Where Men Win Glory: The Odyssey Of Pat Tillman','','Anchor'),
('JOE','HILL','Heart-Shaped Box','','William Morrow'),
('JODI','PICOULT','Nineteen Minutes','','Simon and Schuster'),
('JEFFERY','DEAVER','The Bone Collector','Lincoln Rhyme','Signet Book'),
('JEANNETTE','WALLS','The Glass Castle','','Scribner Book Company'),
('JARED','DIAMOND','Guns, Germs, And Steel: The Fates Of Human Societies','Civilizations Rise And Fall','W.W. Norton & Company'),
('JANET','EVANOVICH','Visions Of Sugar Plums','Stephanie Plum','St. Martins Press'),
('ISAAC','ASIMOV','Foundation And Empire','Foundation, Publication Order','Doubleday'),
('LAURA','HILLENBRAND','Unbroken: A World War Ii Story Of Survival, Resilience And Redemption','','Random House'),
('H. G.','WELLS','A Short History Of The World','','Blackmask Online'),
('GLEN','COOK','The Black Company','The Chronicles Of The Black Company','Tor Books'),
('GEORGE','ORWELL','Animal Farm','','Signet Classics'),
('GENE','WOLFE','Sword & Citadel','The Book Of The New Sun','Orb Books'),
('FYODOR DOSTOYEVSKY; IGNAT','AVSEY','The Karamazov Brothers','The Brothers Karamazov','Oxford University Press'),
('FRIEDRICH','NIETZSCHE','Basic Writings Of Nietzsche','','Random House, Inc.'),
('JONATHAN SAFRAN','FOER','Eating Animals','','Little, Brown and Company'),
('FAYE','KELLERMAN','Stone Kiss','Peter Decker/Rina Lazarus','Hachette UK'),
('F. SCOTT','FITZGERALD','This Side Of Paradise','','C. Scribners Sons'),
('ERIC S.','NYLUND','Halo: First Strike','Halo','Del Rey'),
('EMMA','DONOGHUE','Room','','Picador'),
('LÉONARD','ELMORE','Maximum Bob','','Imprint unknown'),
('ELIE','WIESEL','Night','The Night Trilogy','Penguin'),
('EDGAR ALLAN','POE','Essential Tales And Poems Of Edgar Allan Poe','','Barnes & Noble'),
('DENNIS','LEHANE','Shutter Island','','Harper'),
('CHARLAINE','HARRIS','Living Dead In Dallas','Sookie Stackhouse','Ace Books'),
('CARLOS RUIZ','ZAFÓN','The AngelS Game','El Cementerio De Los Libros Olvidados','Doubleday'),
('BRET EASTON','ELLIS','Imperial Bedrooms','','Knopf'),
('BRENT','WEEKS','Beyond The Shadows','Night Angel','Orbit'),
('BARACK','OBAMA','The Audacity Of Hope: Thoughts On Reclaiming The American Dream','','Vintage'),
('AYN','RAND','The Fountainhead','','Dutton'),
('KATIE','KACVINSKY','Middle Ground','Awaken','Houghton Mifflin Harcourt'),
('ARTHUR C.','CLARKE','ChildhoodS End','','Del Rey'),
('ANNE','RICE','The Tale Of The Body Thief','The Vampire Chronicles','Ballantine Books'),
('ALVIN','TOFFLER','Future Shock','','Bantam'),
('ALISTAIR','MACLEAN','The Way To Dusty Death','','HarperCollins Publishers'),
('RUPI','KAUR','Milk And Honey','','Andrews McMeel Publishing'),
('RAEANNE','THAYNE','Serenity Harbor','Haven Point','HQN Books'),
('RUTH','WARE','The Woman In Cabin 10','','Scout Press'),
('ELIN','HILDERBRAND','The Identicals','','Little, Brown and Company'),
('DANIELLE','STEEL','The Duchess','','Delacorte Press'),
('DIANA','GABALDON','Seven Stones To Stand Or Fall','Outlander','Doubleday Canada'),
('IMBOLO','MBUE','Behold The Dreamers','','Random House Trade'),
('MARTHA HALL','KELLY','Lilac Girls','Lilac Girls','Ballantine Books'),
('FREDRIK','BACKMAN','A Man Called Ove: A Novel','','Atria Books'),
('MARY ALICE','MONROE','Beach House For Rent','Beach House','Gallery Books'),
('ROLF','DOBELLI','The Art Of Thinking Clearly','','Harper'),
('NEIL DEGRASSE','TYSON','Astrophysics For People In A Hurry','','W. W. Norton  Company'),
('NIALL','FERGUSON','Civilization: The West And The Rest','','Allen Lane'),
('ROBERT B.','CIALDINI','Influence: The Psychology Of Persuasion','','Pegasus'),
('HENRY','KISSINGER','World Order','','Penguin Press'),
('ADAM J','SCOTT','Habit Stacking: Learn To Master Your Goals, Improve Your Life, End Procrastination, Increase Productivity To Create Constant Wealth, Happiness, And Success','','CreateSpace Independent Publishing Platform'),
('KEVIN','HORSLEY','Unlimited Memory: How To Use Advanced Learning Strategies To Learn Faster','','CreateSpace Independent Publishing Platform'),
('ROALD','DAHL','The Wonderful Story Of Henry Sugar And Six More','','Penguin UK'),
('JENNET','CONANT','The Irregulars: Roald Dahl And The British Spy Ring In Wartime Washington','','Simon & Schuster'),
('GREG','GUTFELD','How To Be Right: The Art Of Being Persuasively Correct','','Crown Forum'),
('SANDRA M.','REED','Phr / Sphr Exam For Dummies','','For Dummies'),
('JULIEN','AYOTTE','Dangerous Bloodlines','Flower Of Heaven','Create Space'),
('ALFRED','BESTER','The Demolished Man','','Vintage Books'),
('ANDRZEJ','SAPKOWSKI','The Last Wish: Introducing The Witcher','The Witcher','Hachette UK'),
('FREDERICK C.','BEISER','The Cambridge Companion To Hegel And Nineteenth-Century Philosophy','Cambridge Companions To Philosophy','Cambridge University Press'),
('MARKKU','PELTONEN','The Cambridge Companion To Bacon','Cambridge Companions To Philosophy','Cambridge University Press'),
('VERE C.','CHAPPELL','The Cambridge Companion To Locke','Cambridge Companions To Philosophy','Cambridge University Press'),
('DONALD','RUTHERFORD','The Cambridge Companion To Early Modern Philosophy','Cambridge Companions To Philosophy','Cambridge University Press'),
('DANA RICHARD','VILLA','The Cambridge Companion To Hannah Arendt','Cambridge Companions To Philosophy','Cambridge University Press'),
('ANTHONY A.','LONG','The Cambridge Companion To Early Greek Philosophy','Cambridge Companions To Philosophy','Cambridge University Press'),
('MARK A.','WRATHALL','The Cambridge Companion To HeideggerS Being And Time','Cambridge Companions To Philosophy','Cambridge University Press'),
('STEVEN GALT','CROWELL','The Cambridge Companion To Existentialism','Cambridge Companions To Philosophy','Cambridge University Press'),
('KARL','AMERIKS','The Cambridge Companion To German Idealism','Cambridge Companions To Philosophy','Cambridge University Press'),
('BJARNE','STROUSTRUP','Programming: Principles And Practice Using C++','','Addison-Wesley Professional'),
('ANTONY','POLUKHIN','Boost C++ Application Development Cookbook','','Packt Publishing'),
('CONRAD','CARLBERG','Statistical Analysis: Microsoft Excel 2010','','Que'),
('HECTOR','GUERRERO','Excel Data Analysis: Modeling And Simulation','','Springer'),
('WAYNE L.','WINSTON','Microsoft Excel 2010: Data Analysis And Business Modeling','','Microsoft Press'),
('CHANDAN','SENGUPTA','Financial Modeling Using Excel And Vba','','Wiley'),
('K SCOTT','PROCTOR','Building Financial Models With Microsoft Excel','','John Wiley & Sons'),
('THOMAS J.','QUIRK','Excel 2010 For Business Statistics: A Guide To Solving Practical Business Problems','','Springer'),
('ABBOTT','KATZ','Excel 2010 Made Simple','','Apress'),
('ART','TENNICK','Practical Powerpivot & Dax Formulas For Excel 2010','','McGraw-Hill Education'),
('ANDRE','ODNOHA','Excel 2010 Financials Cookbook','','Packt Publishing'),
('MILTON','MICHAEL','Head First Excel','','Shroff - OReilly'),
('Y LAKSHMI','PRASAD','Big Data Analytics Made Easy','','Notion Press, Inc.'),
('ROBERT ANTON','WILSON','Quantum Psychology: How Brain Software Programs You & Your World','','New Falcon'),
('ARTHUR','KURZWEIL','The Torah For Dummies','','John Wiley & Sons'),
('COLIN','BARROW','Business Start Up For Dummies Three E-Book Bundle: Starting A Business For Dummies, Business Plans For Dummies, Understanding Business Accounting For Dummies','','For Dummies'),
('MORRIS','ALTMAN','Behavioral Economics For Dummies','','For Dummies'),
('SVEN','WOMBWELL','Allotment Gardening For Dummies','','For Dummies'),
('ANGELA HOPE','MURRAY','Ayurveda For Dummies','','For Dummies'),
('FOR','DUMMIES','German All-In-One For Dummies','','For Dummies'),
('BRYAN','PERRETT','British Military History For Dummies','','For Dummies'),
('JOYCE LAIN','KENNEDY','Job Interviews For Dummies','','Wiley Publishing'),
('SHERRI','BAPTISTE','Yoga With Weights For Dummies','','For Dummies'),
('KEITH D.','DICKSON','World War Ii For Dummies','','For Dummies'),
('SEAN MASAKI','FLYNN','Economics For Dummies','','For Dummies'),
('MARC','CAMERON','Tom Clancy Power And Empire','Jack Ryan','Penguin'),
('GRANT','BLACKWOOD','Tom Clancy Duty And Honor (A Jack Ryan Jr. Novel)','Jack Ryan Universe','G.P. Putnams Sons'),
('THOMAS A.','BLACKSON','Ancient Greek Philosophy: From The Presocratics To The Hellenistic Philosophers','','Wiley-Blackwell'),
('ROLF H. J.','SCHLEGEL','Concise Encyclopedia Of Crop Improvement: Institutions, Persons, Theories, Methods, And Histories','','CRC Press'),
('STEPHON','ALEXANDER','The Jazz Of Physics: The Secret Link Between Music And The Structure Of The Universe','','Basic Books'),
('CAROL S.','DWECK','Mindset: The New Psychology Of Success','','Random House'),
('EDWIN L.','BATTISTELLA','Sorry About That: The Language Of Public Apology','','OUP Us'),
('WINI','MORANVILLE','The Bonne Femme Cookbook: Simple, Splendid Food That French Women Cook Every Day','','Harvard Common Press'),
('STELLA','WELLER','The Yoga Back Book','','Thorsons Publishers'),
('PHILIP J.','CARTER','The Complete Book Of Intelligence Tests: 500 Exercises To Improve, Upgrade And Enhance Your Mind Strength','','Wiley'),
('LISA','SEE','Dragon Bones','Red Princess','Random House'),
('GAR','ALPEROVITZ','America Beyond Capitalism: Reclaiming Our Wealth, Our Liberty, And Our Democracy','','Wiley'),
('JEN','CAMPBELL','Weird Things Customers Say In Bookshops','Weird Things Customers Say In Bookshops','Constable'),
('GREIG','BECK','Beneath The Dark Ice','Alex Hunter','MacMillan'),
('SUSANNAH','CAHALAN','Brain On Fire: My Month Of Madness','','Free Press'),
('RONALD','KESSLER','In The PresidentS Secret Service: Behind The Scenes With Agents In The Line Of Fire And The Presidents They Protect','','Crown'),
('NASSIM NICHOLAS','TALEB','Antifragile: Things That Gain From Disorder','','Random House'),
('KATHERINE','BOO','Behind The Beautiful Forevers: Life, Death, And Hope In A Mumbai Undercity','','Random House Digital, Inc.'),
('KAY','HOOPER','The First Prophet','Bishop Files','Jove'),
('SYLVIA','NASAR','A Beautiful Mind','','Faber and Faber'),
('BLAINE','HARDEN','Escape From Camp 14: One ManS Remarkable Odyssey From North Korea To Freedom In The West','','Mantle'),
('MIRANDA','BRUCE-MITFORD','The Illustrated Book Of Signs & Symbols','','DK Publishing (Dorling Kindersley)'),
('JULIE CARRICK','DALTON','Waiting For The Night Song','','Tom Doherty Associates'),
('HAYDEN','FINCH','The Psychology Of Procrastination: Understand Your Habits, Find Motivation, And Get Things Done','','Callisto Media Incorporated'),
('JOEL','VOS','The Psychology Of Covid-19: Building Resilience For Future Pandemics','','Sage Publications Ltd'),
('TODD K.','SHACKELFORD','The Sage Handbook Of Evolutionary Psychology','','SAGE PUBN'),
('VLAD','ZACHARY','The Excellence Habit: How Small Changes In Our Mindset Can Make A Big Difference In Our Lives','','Smashwords Edition'),
('MARIE','BENEDICT','The Mystery Of Mrs. Christie','','Thorndike Press Large Print'),
('TERRY','STICKELS','The Big Book Of Mind-Bending Puzzles','','Sterling'),
('JASON','CALLAWAY','Computer Programming: 4 Books In 1: Python Programming, Data Science, Computer Networking For Beginners, Hacking With Kali Linux. Coding Language For Machine Learning And Artificial Intelligence.','','Independently Published'),
('MATEO','ASKARIPOUR','Black Buck','','HMH Books'),
('H.','BIRX','Encyclopedia Of Time 3 Volume Set: Science, Philosophy, Theology, & Culture','','Sage Publications (CA)'),
('JOSEPHA','SHERMAN','Storytelling: An Encyclopedia Of Mythology And Folklore','','Routledge'),
('JACOB DARWIN','HAMBLIN','Science In The Early Twentieth Century: An Encyclopedia','','ABC-CLIO'),
('DEREK','HARVEY','Super Nature Encyclopedia','','DK Children'),
('RUNNERS','WORLD','Complete Guide To WomenS Running','',''),
('LUIS A.','CORDON','Popular Psychology: An Encyclopedia','','Greenwood'),
('EDWARD','CRAIG','The Shorter Routledge Encyclopedia Of Philosophy','','Routledge'),
('FÉLIX','GUIRAND','New Larousse Encyclopedia Of Mythology','','Crescent'),
('OSCAR MORAN','ESQUERDO','Muscle Exercises Encyclopedia','','Meyer & Meyer Sport'),
('E. ALLAN','FARNSWORTH','MagillS Encyclopedia Of Science: Plant Life 4','','Salem Press'),
('CEFN','RIDOUT','Dc Comics Encyclopedia Updated Edition','','DK'),
('BELVA','PLAIN','Les Diamants De LHiver','','Belfond'),
('LOWELL D.','STREIKER','An Encyclopedia Of Humor','','Hendrickson Publishers'),
('BERNHARD','GRZIMEK','GrzimekS Animal Life Encyclopedia: Mammals 15','','Gale'),
('JOHN F.','MCCOY','Geo-Data: World Geographic Encyclopedia','','Gale'),
('JOHN M.','MERRIMAN','Europe - 1789 To 1914 - Encyclopedia Of The Age Of Industry And Empire (Europe)','','Charles Scribners Sons'),
('CINDY C.','COMBS','Encyclopedia Of Terrorism','Facts On File Library Of World History','Facts on File'),
('RITA C.','RICHEY','Encyclopedia Of Terminology For Educational Communications And Technology','','Springer'),
('STEVEN W.','LEE','Encyclopedia Of School Psychology','','Sage Publications, Inc'),
('MICHAEL R.','PERES','The Focal Encyclopedia Of Photography','','Focal Press'),
('CARLO','DEVITO','The Encyclopedia Of International Organized Crime','','Checkmark Books'),
('M. GABRIEL','KHAN','Encyclopedia Of Heart Diseases','','Academic Press'),
('GLENN S.','ROTHFELD','The Facts On File Encyclopedia Of Health And Medicine, 4-Volume Set: A Comprehensive And Concise Guide To The Human Body And Modern Medical Practices','','Facts on File'),
('KRISTIN','KEY','The Gale Encyclopedia Of Diets: A Guide To Health And Nutrition','','Gale Cengage'),
('BARBARA A.','KERR','Encyclopedia Of Giftedness, Creativity, And Talent','','Sage Publications, Inc.'),
('HENK C. A. VAN','TILBORG','Encyclopedia Of Cryptography And Security','','Springer'),
('THOMAS N.','BULKOWSKI','Encyclopedia Of Chart Patterns','','Wiley'),
('SYED B.','HUSSAIN','Encyclopedia Of Capitalism (Facts On File Library Of World History) 3 Vol Set','','Facts on File'),
('JAN HAROLD','BRUNVAND','American Folklore: An Encyclopedia','','Routledge'),
('GARRY','KASPAROV','The Test Of Time','','Pergamon'),
('BERNARD','LENTÉRIC','Substance B.: Roman','','Olivier Orban'),
('ALEKSANDR SERGEYEVICH','PUSHKIN','La Fille Du Capitaine','','Independently Published'),
('WASHINGTON','IRVING','The Legend Of Sleepy Hollow','','Wildside Press'),
('FYODOR','DOSTOYEVSKY','Demons','','Vintage Books'),
('MIA','COUTO','Terra Sonâmbula','','Companhia das Letras'),
('JAMES FENIMORE','COOPER','The Last Of The Mohicans','The Leatherstocking Tales','Bantam Classics'),
('MIKHAIL','BULGAKOV','The Master And Margarita','','Penguin Books'),
('HONORÉ DE','BALZAC','Eugénie Grandet','La Comédie Humaine','Oxford University Press'),
('J. G.','BALLARD','High-Rise','','4th Estate'),
('FAITH','ANDREWS','Back To You','Dreams','CreateSpace Independent Publishing Platform'),
('TAMMY','STROBEL','You Can Buy Happiness (And ItS Cheap): How One Woman Radically Simplified Her Life And How You Can Too','','New World Library'),
('SAM','LEITH','Write To The Point How To Be Clear, Correct And Persuasive On The Page','','Profile Books'),
('RACHEL','HAYNES','What DoesnT Kill You','','Watkins'),
('KAVITA','DEVGAN','Ultimate Grandmother Hacks: 50 Kickass Traditional Habits For A Fitter You','','amazon'),
('OPRAH','WINFREY','The Path Made Clear: Discovering Your LifeS Direction And Purpose','','Flatiron Books'),
('HAL','ELROD','The Miracle Morning Journal','','Miracle Morning Publishing, LLC'),
('REGINA','ROSENTHAL','The Heart Of Healing: Discovering The Secrets Of Self-Care','','BookBaby'),
('PETR','LUDWIG','The End Of Procrastination: How To Stop Postponing And Live A Fulfilled Life','','St. Martins Press'),
('DEBBIE','FORD','The Dark Side Of The Light Chasers: Reclaiming Your Power, Creativity, Brilliance And Dreams','','Penguin Publishing Group'),
('EMILY','MILLS','The Art Of Visual Notetaking: An Interactive Guide To Visual Communication And Sketchnoting','','Walter Foster Publishing'),
('JOCELYN R','DAVIS','The Art Of Quiet Influence: Eastern Wisdom And Mindfulness For Work And Life: Confucius, Rumi, Gandhi, The Buddha, Taoists, Zen Masters, And More','','Quercus'),
('RYUHO','OKAWA','The Art Of Influence: 28 Ways To Win PeopleS Hearts And Bring Positive Change To Your Life','','IRH Press'),
('DUMMIES','PRESS','Success Habits For Dummies','','Wiley'),
('MINA','SAMUELS','Run Like A Girl 365 Days A Year: A Practical, Personal, Inspirational Guide For Women Athletes','','Skyhorse'),
('JOSEPH A.','ANNIBALI','Reclaim Your Brain: How To Calm Your Thoughts, Heal Your Mind, And Bring Your Life Back Under Control','','Penguin Publishing Group'),
('READERS DIGEST','ASSOCIATION','ReaderS Digest Everyday Survival Hacks','','Readers Digest'),
('JENNIFER BUTLER','GREEN','Social Skills: Overcoming Social Anxiety And Improve Your Social Skills','',''),
('W. ROBERT','NAY','Overcoming Anger In Your Relationship: How To Break The Cycle Of Arguments, Put-Downs, And Stony Silences','','Guilford Publications'),
('CRESSON H.','KEARNY','Nuclear War Survival Skills: Lifesaving Nuclear Facts And Self-Help Instructions','','Skyhorse Publishing'),
('SARA ELLIOTT','PRICE','Meditation For Beginners: How To Meditate For Lifelong Peace, Focus And Happiness','','Success Life Publishing'),
('TANA','FRENCH','In The Woods','Dublin Murder Squad','Penguin'),
('PAUL J.','SILVIA','How To Write A Lot: A Practical Guide To Productive Academic Writing','','American Psychological Association'),
('ADAMS','MEDIA','Happiness Hacks: 300+ Simple Ways To Get—And Stay—Happy','','Adams Media'),
('RYAN','HOLIDAY','Ego Is The Enemy','','Portfolio'),
('JOSIANE','BALASKO','Cliente','','Le Livre de Poche'),
('JACQUI','OLLIVER','Doing This One Thing Will Change Your Life Forever!','','Educate Publishing'),
('YUMI','SAKUGAWA','There Is No Right Way To Meditate: And Other Lessons','','F+W Media'),
('NANCY DAVIS','KHO','The Thank-You Project: Cultivating Happiness One Letter Of Gratitude At A Time','','Running Press'),
('KRISTINE KATHRYN','RUSCH','The Pursuit Of Perfection: And How It Harms Writers','','WMG Publishing, Inc.'),
('BRIAN E.','HOWARD','The Motivated College Graduate: A Job Search Book For Recent College Graduates','','WriteLife Publishing'),
('DAYNA','LEE-BAGGLEY','Healthy Habits Suck: How To Get Off The Couch And Live A Healthy Life… Even If You Don’T Want To','','New Harbinger Publications'),
('HORST','SCHULZE','Excellence Wins: A No-Nonsense Guide To Becoming The Best In A World Of Compromise','','Zondervan'),
('MICHELLE TILLIS','LEDERMAN','The 11 Laws Of Likability: Relationship Networking . . . Because People Do Business With People They Like','',''),
('ROBERT L','JOLLES','How To Change Minds: The Art Of Influence Without Manipulation','',''),
('NICOLE','LEPERA','How To Do The Work: Recognize Your Patterns, Heal From Your Past, And Create Your Self','','Hachette UK'),
('WILLIAM MC','DOUGALL','An Introduction To Social Psychology','',''),
('NOAH ST.','JOHN','The Book Of Afformations: Discovering The Missing Piece To Abundant Health, Wealth, Love, And Happiness','','Hay House'),
('SHELLY','WU','Chinese Astrology: Exploring The Eastern Zodiac','',''),
('ROMULUS','HILLSBOROUGH','Shinsengumi: The ShogunS Last Samurai Corps','',''),
('WIM','HOF','The Wim Hof Method: Activate Your Potential, Transcend Your Limits','','Ebury Publishing'),
('ZAKARIYA','ADEEL','Secrets Of The Combined Astrology: The Full 144 Combinations Of The Chinese & Western Zodiac Signs','','John Hunt Publishing'),
('SIMON','COLLIN','Eating Out In Five Languages','',''),
('PAUL','TREMBLAY','A Head Full Of Ghosts','',''),
('JEREMY','BATES','Suicide Forest','WorldS Scariest Places','Ghillinnein Books'),
('PATRICIA','HIGHSMITH','The Talented Mr Ripley','Ripley','Vintage'),
('CONOR','OCLERY','Billionaire Who WasnT: How Chuck Feeney Made And Gave Away A Fortune','','PublicAffairs')

;